/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AiRouteImport } from './routes/ai'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as CyberSecurityRouteImport } from './routes/cyber-security'
import { Route as DataSceineceRouteImport } from './routes/data-sceinece'
import { Route as FullStackDevelopmentRouteImport } from './routes/full-stack-development'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as InnovationLabRouteImport } from './routes/innovation-lab'
import { Route as ItStaffingRouteImport } from './routes/it-staffing'
import { Route as ItStaffingAndConsultingRouteImport } from './routes/it-staffing-and-consulting'
import { Route as SoftwareDevelopmentRouteImport } from './routes/software-development'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TrainingAndInnovationRouteImport } from './routes/training-and-innovation'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as ProjectPagesSplatRouteImport } from './routes/project-pages.$'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesArtificialIntelligenceRouteImport } from './routes/services.artificial-intelligence'
import { Route as ServicesCybersecurityRouteImport } from './routes/services.cybersecurity'
import { Route as ServicesDataScienceEngineeringRouteImport } from './routes/services.data-science-engineering'
import { Route as ServicesFullStackDevelopmentRouteImport } from './routes/services.full-stack-development'
import { Route as ServicesItStaffingRouteImport } from './routes/services.it-staffing'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services.software-development'
import { Route as ServicesTechnologyConsultingRouteImport } from './routes/services.technology-consulting'
import { Route as SkillsLabIndexRouteImport } from './routes/skills-lab.index'
import { Route as SkillsLabTrainingRouteImport } from './routes/skills-lab.training'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberSecurityRoute = CyberSecurityRouteImport.update({
  id: '/cyber-security',
  path: '/cyber-security',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSceineceRoute = DataSceineceRouteImport.update({
  id: '/data-sceinece',
  path: '/data-sceinece',
  getParentRoute: () => rootRouteImport,
} as any)
const FullStackDevelopmentRoute = FullStackDevelopmentRouteImport.update({
  id: '/full-stack-development',
  path: '/full-stack-development',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationLabRoute = InnovationLabRouteImport.update({
  id: '/innovation-lab',
  path: '/innovation-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ItStaffingRoute = ItStaffingRouteImport.update({
  id: '/it-staffing',
  path: '/it-staffing',
  getParentRoute: () => rootRouteImport,
} as any)
const ItStaffingAndConsultingRoute = ItStaffingAndConsultingRouteImport.update({
  id: '/it-staffing-and-consulting',
  path: '/it-staffing-and-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareDevelopmentRoute = SoftwareDevelopmentRouteImport.update({
  id: '/software-development',
  path: '/software-development',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingAndInnovationRoute = TrainingAndInnovationRouteImport.update({
  id: '/training-and-innovation',
  path: '/training-and-innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectPagesSplatRoute = ProjectPagesSplatRouteImport.update({
  id: '/project-pages/$',
  path: '/project-pages/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesArtificialIntelligenceRoute =
  ServicesArtificialIntelligenceRouteImport.update({
    id: '/services/artificial-intelligence',
    path: '/services/artificial-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCybersecurityRoute = ServicesCybersecurityRouteImport.update({
  id: '/services/cybersecurity',
  path: '/services/cybersecurity',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDataScienceEngineeringRoute =
  ServicesDataScienceEngineeringRouteImport.update({
    id: '/services/data-science-engineering',
    path: '/services/data-science-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFullStackDevelopmentRoute =
  ServicesFullStackDevelopmentRouteImport.update({
    id: '/services/full-stack-development',
    path: '/services/full-stack-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesItStaffingRoute = ServicesItStaffingRouteImport.update({
  id: '/services/it-staffing',
  path: '/services/it-staffing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/services/software-development',
    path: '/services/software-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesTechnologyConsultingRoute =
  ServicesTechnologyConsultingRouteImport.update({
    id: '/services/technology-consulting',
    path: '/services/technology-consulting',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsLabIndexRoute = SkillsLabIndexRouteImport.update({
  id: '/skills-lab/',
  path: '/skills-lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsLabTrainingRoute = SkillsLabTrainingRouteImport.update({
  id: '/skills-lab/training',
  path: '/skills-lab/training',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai': typeof AiRoute
  '/careers': typeof CareersRoute
  '/consulting': typeof ConsultingRoute
  '/cyber-security': typeof CyberSecurityRoute
  '/data-sceinece': typeof DataSceineceRoute
  '/full-stack-development': typeof FullStackDevelopmentRoute
  '/industries': typeof IndustriesRoute
  '/innovation': typeof InnovationRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/it-staffing': typeof ItStaffingRoute
  '/it-staffing-and-consulting': typeof ItStaffingAndConsultingRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/training': typeof TrainingRoute
  '/training-and-innovation': typeof TrainingAndInnovationRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/project-pages/$': typeof ProjectPagesSplatRoute
  '/services/artificial-intelligence': typeof ServicesArtificialIntelligenceRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-science-engineering': typeof ServicesDataScienceEngineeringRoute
  '/services/full-stack-development': typeof ServicesFullStackDevelopmentRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/technology-consulting': typeof ServicesTechnologyConsultingRoute
  '/skills-lab/training': typeof SkillsLabTrainingRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/skills-lab/': typeof SkillsLabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai': typeof AiRoute
  '/careers': typeof CareersRoute
  '/consulting': typeof ConsultingRoute
  '/cyber-security': typeof CyberSecurityRoute
  '/data-sceinece': typeof DataSceineceRoute
  '/full-stack-development': typeof FullStackDevelopmentRoute
  '/industries': typeof IndustriesRoute
  '/innovation': typeof InnovationRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/it-staffing': typeof ItStaffingRoute
  '/it-staffing-and-consulting': typeof ItStaffingAndConsultingRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/training': typeof TrainingRoute
  '/training-and-innovation': typeof TrainingAndInnovationRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/project-pages/$': typeof ProjectPagesSplatRoute
  '/services/artificial-intelligence': typeof ServicesArtificialIntelligenceRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-science-engineering': typeof ServicesDataScienceEngineeringRoute
  '/services/full-stack-development': typeof ServicesFullStackDevelopmentRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/technology-consulting': typeof ServicesTechnologyConsultingRoute
  '/skills-lab/training': typeof SkillsLabTrainingRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/skills-lab': typeof SkillsLabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/ai': typeof AiRoute
  '/careers': typeof CareersRoute
  '/consulting': typeof ConsultingRoute
  '/cyber-security': typeof CyberSecurityRoute
  '/data-sceinece': typeof DataSceineceRoute
  '/full-stack-development': typeof FullStackDevelopmentRoute
  '/industries': typeof IndustriesRoute
  '/innovation': typeof InnovationRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/it-staffing': typeof ItStaffingRoute
  '/it-staffing-and-consulting': typeof ItStaffingAndConsultingRoute
  '/software-development': typeof SoftwareDevelopmentRoute
  '/training': typeof TrainingRoute
  '/training-and-innovation': typeof TrainingAndInnovationRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/project-pages/$': typeof ProjectPagesSplatRoute
  '/services/artificial-intelligence': typeof ServicesArtificialIntelligenceRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-science-engineering': typeof ServicesDataScienceEngineeringRoute
  '/services/full-stack-development': typeof ServicesFullStackDevelopmentRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/technology-consulting': typeof ServicesTechnologyConsultingRoute
  '/skills-lab/training': typeof SkillsLabTrainingRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/skills-lab/': typeof SkillsLabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/ai'
    | '/careers'
    | '/consulting'
    | '/cyber-security'
    | '/data-sceinece'
    | '/full-stack-development'
    | '/industries'
    | '/innovation'
    | '/innovation-lab'
    | '/it-staffing'
    | '/it-staffing-and-consulting'
    | '/software-development'
    | '/training'
    | '/training-and-innovation'
    | '/what-we-do'
    | '/project-pages/$'
    | '/services/artificial-intelligence'
    | '/services/cybersecurity'
    | '/services/data-science-engineering'
    | '/services/full-stack-development'
    | '/services/it-staffing'
    | '/services/software-development'
    | '/services/technology-consulting'
    | '/skills-lab/training'
    | '/case-studies/'
    | '/services/'
    | '/skills-lab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/ai'
    | '/careers'
    | '/consulting'
    | '/cyber-security'
    | '/data-sceinece'
    | '/full-stack-development'
    | '/industries'
    | '/innovation'
    | '/innovation-lab'
    | '/it-staffing'
    | '/it-staffing-and-consulting'
    | '/software-development'
    | '/training'
    | '/training-and-innovation'
    | '/what-we-do'
    | '/project-pages/$'
    | '/services/artificial-intelligence'
    | '/services/cybersecurity'
    | '/services/data-science-engineering'
    | '/services/full-stack-development'
    | '/services/it-staffing'
    | '/services/software-development'
    | '/services/technology-consulting'
    | '/skills-lab/training'
    | '/case-studies'
    | '/services'
    | '/skills-lab'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/ai'
    | '/careers'
    | '/consulting'
    | '/cyber-security'
    | '/data-sceinece'
    | '/full-stack-development'
    | '/industries'
    | '/innovation'
    | '/innovation-lab'
    | '/it-staffing'
    | '/it-staffing-and-consulting'
    | '/software-development'
    | '/training'
    | '/training-and-innovation'
    | '/what-we-do'
    | '/project-pages/$'
    | '/services/artificial-intelligence'
    | '/services/cybersecurity'
    | '/services/data-science-engineering'
    | '/services/full-stack-development'
    | '/services/it-staffing'
    | '/services/software-development'
    | '/services/technology-consulting'
    | '/skills-lab/training'
    | '/case-studies/'
    | '/services/'
    | '/skills-lab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AiRoute: typeof AiRoute
  CareersRoute: typeof CareersRoute
  ConsultingRoute: typeof ConsultingRoute
  CyberSecurityRoute: typeof CyberSecurityRoute
  DataSceineceRoute: typeof DataSceineceRoute
  FullStackDevelopmentRoute: typeof FullStackDevelopmentRoute
  IndustriesRoute: typeof IndustriesRoute
  InnovationRoute: typeof InnovationRoute
  InnovationLabRoute: typeof InnovationLabRoute
  ItStaffingRoute: typeof ItStaffingRoute
  ItStaffingAndConsultingRoute: typeof ItStaffingAndConsultingRoute
  SoftwareDevelopmentRoute: typeof SoftwareDevelopmentRoute
  TrainingRoute: typeof TrainingRoute
  TrainingAndInnovationRoute: typeof TrainingAndInnovationRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  ProjectPagesSplatRoute: typeof ProjectPagesSplatRoute
  ServicesArtificialIntelligenceRoute: typeof ServicesArtificialIntelligenceRoute
  ServicesCybersecurityRoute: typeof ServicesCybersecurityRoute
  ServicesDataScienceEngineeringRoute: typeof ServicesDataScienceEngineeringRoute
  ServicesFullStackDevelopmentRoute: typeof ServicesFullStackDevelopmentRoute
  ServicesItStaffingRoute: typeof ServicesItStaffingRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
  ServicesTechnologyConsultingRoute: typeof ServicesTechnologyConsultingRoute
  SkillsLabTrainingRoute: typeof SkillsLabTrainingRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SkillsLabIndexRoute: typeof SkillsLabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-security': {
      id: '/cyber-security'
      path: '/cyber-security'
      fullPath: '/cyber-security'
      preLoaderRoute: typeof CyberSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sceinece': {
      id: '/data-sceinece'
      path: '/data-sceinece'
      fullPath: '/data-sceinece'
      preLoaderRoute: typeof DataSceineceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/full-stack-development': {
      id: '/full-stack-development'
      path: '/full-stack-development'
      fullPath: '/full-stack-development'
      preLoaderRoute: typeof FullStackDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-lab': {
      id: '/innovation-lab'
      path: '/innovation-lab'
      fullPath: '/innovation-lab'
      preLoaderRoute: typeof InnovationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-staffing': {
      id: '/it-staffing'
      path: '/it-staffing'
      fullPath: '/it-staffing'
      preLoaderRoute: typeof ItStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-staffing-and-consulting': {
      id: '/it-staffing-and-consulting'
      path: '/it-staffing-and-consulting'
      fullPath: '/it-staffing-and-consulting'
      preLoaderRoute: typeof ItStaffingAndConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-development': {
      id: '/software-development'
      path: '/software-development'
      fullPath: '/software-development'
      preLoaderRoute: typeof SoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-and-innovation': {
      id: '/training-and-innovation'
      path: '/training-and-innovation'
      fullPath: '/training-and-innovation'
      preLoaderRoute: typeof TrainingAndInnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-pages/$': {
      id: '/project-pages/$'
      path: '/project-pages/$'
      fullPath: '/project-pages/$'
      preLoaderRoute: typeof ProjectPagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/artificial-intelligence': {
      id: '/services/artificial-intelligence'
      path: '/services/artificial-intelligence'
      fullPath: '/services/artificial-intelligence'
      preLoaderRoute: typeof ServicesArtificialIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cybersecurity': {
      id: '/services/cybersecurity'
      path: '/services/cybersecurity'
      fullPath: '/services/cybersecurity'
      preLoaderRoute: typeof ServicesCybersecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/data-science-engineering': {
      id: '/services/data-science-engineering'
      path: '/services/data-science-engineering'
      fullPath: '/services/data-science-engineering'
      preLoaderRoute: typeof ServicesDataScienceEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/full-stack-development': {
      id: '/services/full-stack-development'
      path: '/services/full-stack-development'
      fullPath: '/services/full-stack-development'
      preLoaderRoute: typeof ServicesFullStackDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/it-staffing': {
      id: '/services/it-staffing'
      path: '/services/it-staffing'
      fullPath: '/services/it-staffing'
      preLoaderRoute: typeof ServicesItStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/services/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/technology-consulting': {
      id: '/services/technology-consulting'
      path: '/services/technology-consulting'
      fullPath: '/services/technology-consulting'
      preLoaderRoute: typeof ServicesTechnologyConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-lab/': {
      id: '/skills-lab/'
      path: '/skills-lab'
      fullPath: '/skills-lab/'
      preLoaderRoute: typeof SkillsLabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills-lab/training': {
      id: '/skills-lab/training'
      path: '/skills-lab/training'
      fullPath: '/skills-lab/training'
      preLoaderRoute: typeof SkillsLabTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AiRoute: AiRoute,
  CareersRoute: CareersRoute,
  ConsultingRoute: ConsultingRoute,
  CyberSecurityRoute: CyberSecurityRoute,
  DataSceineceRoute: DataSceineceRoute,
  FullStackDevelopmentRoute: FullStackDevelopmentRoute,
  IndustriesRoute: IndustriesRoute,
  InnovationRoute: InnovationRoute,
  InnovationLabRoute: InnovationLabRoute,
  ItStaffingRoute: ItStaffingRoute,
  ItStaffingAndConsultingRoute: ItStaffingAndConsultingRoute,
  SoftwareDevelopmentRoute: SoftwareDevelopmentRoute,
  TrainingRoute: TrainingRoute,
  TrainingAndInnovationRoute: TrainingAndInnovationRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  ProjectPagesSplatRoute: ProjectPagesSplatRoute,
  ServicesArtificialIntelligenceRoute: ServicesArtificialIntelligenceRoute,
  ServicesCybersecurityRoute: ServicesCybersecurityRoute,
  ServicesDataScienceEngineeringRoute: ServicesDataScienceEngineeringRoute,
  ServicesFullStackDevelopmentRoute: ServicesFullStackDevelopmentRoute,
  ServicesItStaffingRoute: ServicesItStaffingRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
  ServicesTechnologyConsultingRoute: ServicesTechnologyConsultingRoute,
  SkillsLabTrainingRoute: SkillsLabTrainingRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SkillsLabIndexRoute: SkillsLabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
